/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.ManageTravelAgency;

import Business.TravelAgency;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author sachin
 */
public class TravelAgencyHomeJPanel extends javax.swing.JPanel {

    /**
     * Creates new form TravelAgencyHomeJPanel
     */
     private JPanel userProcessContainer;
    private TravelAgency travelAgency;
            

    public TravelAgencyHomeJPanel(JPanel userProcessContainer, TravelAgency travelAgency) {
        
         initComponents();
         
         this.userProcessContainer= userProcessContainer;
         this.travelAgency= travelAgency;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        manageAirlinerJButton = new javax.swing.JButton();
        viewFlightsJButton = new javax.swing.JButton();
        manageCustomerJButton = new javax.swing.JButton();

        manageAirlinerJButton.setText("Manage Airliner");
        manageAirlinerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageAirlinerJButtonActionPerformed(evt);
            }
        });

        viewFlightsJButton.setText("View Flights");
        viewFlightsJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewFlightsJButtonActionPerformed(evt);
            }
        });

        manageCustomerJButton.setText("Manage Customers");
        manageCustomerJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageCustomerJButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(manageCustomerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(viewFlightsJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageAirlinerJButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(611, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(manageAirlinerJButton)
                .addGap(63, 63, 63)
                .addComponent(viewFlightsJButton)
                .addGap(68, 68, 68)
                .addComponent(manageCustomerJButton)
                .addContainerGap(407, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 800, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 673, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void manageAirlinerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageAirlinerJButtonActionPerformed
        // TODO add your handling code here:

        ManageAirlinerJPanel panel= new ManageAirlinerJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageAirlinerJPanel", panel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);

    }//GEN-LAST:event_manageAirlinerJButtonActionPerformed

    private void viewFlightsJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewFlightsJButtonActionPerformed
        // TODO add your handling code here:
        ViewFlightsJPanel panel= new ViewFlightsJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("ViewFlightsJPanel", panel);
        CardLayout layout= (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_viewFlightsJButtonActionPerformed

    private void manageCustomerJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageCustomerJButtonActionPerformed
        // TODO add your handling code here:

        ManageCustomerJPanel panel= new ManageCustomerJPanel(userProcessContainer, travelAgency);
        userProcessContainer.add("ManageCustomerJPanel", panel);
        CardLayout layout= (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_manageCustomerJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton manageAirlinerJButton;
    private javax.swing.JButton manageCustomerJButton;
    private javax.swing.JButton viewFlightsJButton;
    // End of variables declaration//GEN-END:variables
}
